services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=demo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d demo --user demo" ]
      start_period: 30s
      start_interval: 2s
      retries: 10
volumes:
  postgres: