@startmindmap
* Creative-Mind
** positiv
*** Projektteam
*** Auftraggeber->Scrum Master
*** Expertenkontakt
** negativ
*** Technologieeinschrenkung durch den Projektauftraggeber
** neutral
*** Konkurenz
@endmindmap